#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require 'fileutils'

workling = File.join(File.dirname(__FILE__), '..', 'vendor', 'plugins', 'workling', 'script', 'listen.rb')

# get the hostname
 hostname = `hostname`.chomp

#creating the host specific directory for the log
 log_dir = File.join(File.dirname(__FILE__),"../log/#{hostname}")
 unless File.directory? log_dir
  FileUtils.mkdir log_dir
 end

options = {
  :app_name   => "workling",
  :ARGV       => ARGV,
  :dir_mode   => :normal,
  :dir        => log_dir,
  :log_output => true,
  :multiple   => false,
  :backtrace  => true,
  :monitor    => true
}

Daemons.run(workling, options)
